### ISSUE TITLE
Missing duration

### ISSUE THREAD

**Issue by binarykitchen** [TooTallNate/node-wav#20]
It seems that all wav wiles written by the one `WavFileWriter` in this package do not have a duration set in their meta data. Not sure but makes me wonder if that's not a bug?

**Comment by fjn2** [comment]
Could we expose the property in the 'format' event?
In the method **Reader.prototype._onSubchunk1**
```
var format = {
    audioFormat: this.audioFormat,
    endianness: this.endianness,
    channels: this.channels,
    chunkSize: this.chunkSize, // <- add it here
    sampleRate: this.sampleRate,
    byteRate: this.byteRate,
    blockAlign: this.blockAlign,
    bitDepth: this.bitDepth,
    signed: this.signed
  };
```

Adding this information anyone will be able to calculate the audio duration.

What do you think?

**Comment by LinusU** [comment]
@fjn2 I think that the original bug here is talking about the WAV-writer, not the reader.

@binarykitchen This is documented behaviour, and I don't see how we can work around it with how streams works:

> Note that there's an interesting problem, because the WAVE header also specifies the total byte length of the audio data in the file, and there's no way that we can know this ahead of time. Therefore the WAVE header will contain a byte-length if `0` initially, which most WAVE decoders will know means to just read until `EOF`.

[ref](https://github.com/TooTallNate/node-wav#writeroptions)

**Comment by fjn2** [comment]
Hi @LinusU Regarding the duration for the `Reader`. I may add the duration formula as a property in the **format** event (when it is not a stream). Do you prefere to handle this in a different issue?

**Comment by LinusU** [comment]
Yeah, please open a new issue. PRs welcome 🙌
