### ISSUE TITLE
How to play the stream wav file multiple times on demand?

### ISSUE THREAD

**Issue by henryoliver** [TooTallNate/node-wav#26]
Hey guys, following the example below:

```
var fs = require('fs');
var wav = require('wav');
var Speaker = require('speaker');

var file = fs.createReadStream('track01.wav');
var reader = new wav.Reader();

// the "format" event gets emitted at the end of the WAVE header
reader.on('format', function (format) {

  // the WAVE header is stripped from the output of the reader
  reader.pipe(new Speaker(format));
});

// pipe the WAVE file to the Reader instance
file.pipe(reader);
```

How could I call `file.pipe(reader)` multiple times in order to play the same `ding.wav` sound over and over again as needed without memory leak (adding more emit listeners)?

Could you give me some examples triggering the `.wav` file on a separate function on demand?

Thank you for the help! Appreciate it!

Awesome job on this library by the way! :)

**Comment by LinusU** [comment]
Hey!

Unfortunately, this question falls outside the scope of this module, I would recommend posting to [StackOverflow](https://stackoverflow.com).

Good luck!
