### ISSUE TITLE
License document

### ISSUE THREAD

**Issue by Kandy16** [TooTallNate/node-wav#9]
Hey,
 Thanks for the good effort in building this library. We would like to use your node in our project. 

Can you let us know what license have been assigned to this library?

Thanks
Kandy

**Comment by Kandy16** [comment]
Hey Everyone,

We have built a commercial application using your node and have hold our release because of the lack of license information of this particular module. There is a bit of urgency and pressure on us to make the release.

I request you to reveal the license information as soon as possible which will be very helpful for us.

Thanks In Advance
Kandy

**Comment by Kandy16** [comment]
Hey Everyone,

We have built a commercial application using your node and have hold our release because of the lack of license information of this particular module. There is a bit of urgency and pressure on us to make the release.

I request you to reveal the license information as soon as possible which will be very helpful for us.

Thanks In Advance
Kandy

**Comment by TooTallNate** [comment]
It's MIT. I've added a LICENSE file in 3f81b99dcb8a91f41adc73b5b5c1998afe5f4eed. Thanks for the poke!

**Comment by Kandy16** [comment]
Thanks TooTallNate for a quick response.

And many Thanks for the library :-)
